-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 22:50:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` BIGINT NOT NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `apellido_usuario` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `nick` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`juego` (
  `idjuego` BIGINT NOT NULL,
  PRIMARY KEY (`idjuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personaje` (
  `idpersonaje` BIGINT NOT NULL,
  `nombre_personaje` VARCHAR(45) NULL,
  `aspecto_personaje` VARCHAR(45) NULL,
  `estatura_personaje` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `usuario_idusuario` BIGINT NOT NULL,
  `juego_idjuego` BIGINT NOT NULL,
  PRIMARY KEY (`idpersonaje`, `usuario_idusuario`, `juego_idjuego`),
  INDEX `fk_personaje_usuario_idx` (`usuario_idusuario` ASC),
  INDEX `fk_personaje_juego1_idx` (`juego_idjuego` ASC),
  CONSTRAINT `fk_personaje_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personaje_juego1`
    FOREIGN KEY (`juego_idjuego`)
    REFERENCES `mydb`.`juego` (`idjuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escenario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escenario` (
  `idescenario` BIGINT NOT NULL,
  `lugar` VARCHAR(45) NULL,
  `juego_idjuego` BIGINT NOT NULL,
  PRIMARY KEY (`idescenario`, `juego_idjuego`),
  INDEX `fk_escenario_juego1_idx` (`juego_idjuego` ASC),
  CONSTRAINT `fk_escenario_juego1`
    FOREIGN KEY (`juego_idjuego`)
    REFERENCES `mydb`.`juego` (`idjuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nivel` (
  `idnivel` BIGINT NOT NULL,
  `objetivos_juego` VARCHAR(45) NULL,
  PRIMARY KEY (`idnivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escenario_nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escenario_nivel` (
  `idescenario_nivel` BIGINT NOT NULL,
  `escenario_idescenario` BIGINT NOT NULL,
  `escenario_juego_idjuego` BIGINT NOT NULL,
  `nivel_idnivel` BIGINT NOT NULL,
  PRIMARY KEY (`idescenario_nivel`, `escenario_idescenario`, `escenario_juego_idjuego`, `nivel_idnivel`),
  INDEX `fk_escenario_nivel_escenario1_idx` (`escenario_idescenario` ASC, `escenario_juego_idjuego` ASC),
  INDEX `fk_escenario_nivel_nivel1_idx` (`nivel_idnivel` ASC),
  CONSTRAINT `fk_escenario_nivel_escenario1`
    FOREIGN KEY (`escenario_idescenario` , `escenario_juego_idjuego`)
    REFERENCES `mydb`.`escenario` (`idescenario` , `juego_idjuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escenario_nivel_nivel1`
    FOREIGN KEY (`nivel_idnivel`)
    REFERENCES `mydb`.`nivel` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`puntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`puntos` (
  `idpuntos` BIGINT NOT NULL,
  `puntos_acumulados` VARCHAR(45) NULL,
  `nivel_idnivel` BIGINT NOT NULL,
  PRIMARY KEY (`idpuntos`, `nivel_idnivel`),
  INDEX `fk_puntos_nivel1_idx` (`nivel_idnivel` ASC),
  CONSTRAINT `fk_puntos_nivel1`
    FOREIGN KEY (`nivel_idnivel`)
    REFERENCES `mydb`.`nivel` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tiempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tiempo` (
  `idtiempo` BIGINT NOT NULL,
  `tiempo_acumulado` VARCHAR(45) NULL,
  `nivel_idnivel` BIGINT NOT NULL,
  PRIMARY KEY (`idtiempo`, `nivel_idnivel`),
  INDEX `fk_tiempo_nivel1_idx` (`nivel_idnivel` ASC),
  CONSTRAINT `fk_tiempo_nivel1`
    FOREIGN KEY (`nivel_idnivel`)
    REFERENCES `mydb`.`nivel` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enemigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enemigo` (
  `idenemigo` BIGINT NOT NULL,
  `nombre_enemigo` VARCHAR(45) NULL,
  `apariencia` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  PRIMARY KEY (`idenemigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enemigo_esce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enemigo_esce` (
  `idenemigo_esce` BIGINT NOT NULL,
  `escenario_idescenario` BIGINT NOT NULL,
  `escenario_juego_idjuego` BIGINT NOT NULL,
  `enemigo_idenemigo` BIGINT NOT NULL,
  PRIMARY KEY (`idenemigo_esce`, `escenario_idescenario`, `escenario_juego_idjuego`, `enemigo_idenemigo`),
  INDEX `fk_enemigo_esce_escenario1_idx` (`escenario_idescenario` ASC, `escenario_juego_idjuego` ASC),
  INDEX `fk_enemigo_esce_enemigo1_idx` (`enemigo_idenemigo` ASC),
  CONSTRAINT `fk_enemigo_esce_escenario1`
    FOREIGN KEY (`escenario_idescenario` , `escenario_juego_idjuego`)
    REFERENCES `mydb`.`escenario` (`idescenario` , `juego_idjuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enemigo_esce_enemigo1`
    FOREIGN KEY (`enemigo_idenemigo`)
    REFERENCES `mydb`.`enemigo` (`idenemigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
